const db = require("../models");
const assetProfile = db.assetProfile;

async function initializeAssetProfile() {
  const profiles = [
    {
      profileId: 1,
      profileName: "iPhone 13",
      typeId: 1,
      notes: "Apple smartphone with A15 Bionic chip.",
      purchasePrice: 999.99,
      acquisitionDate: "2024-03-29 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 2,
      profileName: "Samsung Galaxy S21",
      typeId: 1,
      notes: "Android smartphone with high-resolution camera.",
      purchasePrice: 899.99,
      acquisitionDate: "2024-02-28 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 3,
      profileName: "Dell XPS 15",
      typeId: 2,
      notes: "High-performance laptop with Intel Core i7 processor.",
      purchasePrice: 1499.99,
      acquisitionDate: "2023-12-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 4,
      profileName: 'MacBook Pro 16"',
      typeId: 2,
      notes: "Apple laptop with M1 Pro chip.",
      purchasePrice: 1999.99,
      acquisitionDate: "2023-10-05 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 5,
      profileName: "iPad Pro",
      typeId: 3,
      notes: "Apple tablet with Liquid Retina display.",
      purchasePrice: 799.99,
      acquisitionDate: "2023-08-20 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 6,
      profileName: "Lenovo ThinkPad X1 Carbon",
      typeId: 2,
      notes: "Ultralight business laptop with Intel Core i7 processor.",
      purchasePrice: 1299.99,
      acquisitionDate: "2023-06-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 7,
      profileName: "Canon EOS R5",
      typeId: 11,
      notes: "Professional mirrorless camera.",
      purchasePrice: 3499.99,
      acquisitionDate: "2023-04-30 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 8,
      profileName: "Sony Alpha A7 III",
      typeId: 11,
      notes: "Full-frame mirrorless camera with advanced autofocus.",
      purchasePrice: 1999.99,
      acquisitionDate: "2023-03-01 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 9,
      profileName: "Poly Studio X50",
      typeId: 12,
      notes: "Video conferencing bar with 4K support.",
      purchasePrice: 2499.99,
      acquisitionDate: "2022-12-25 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 10,
      profileName: "Google Pixel 6",
      typeId: 1,
      notes: "Android smartphone with Google Tensor processor.",
      purchasePrice: 799.99,
      acquisitionDate: "2022-10-10 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 11,
      profileName: "HP Spectre x360",
      typeId: 2,
      notes: "Convertible laptop with touch screen and pen support.",
      purchasePrice: 1599.99,
      acquisitionDate: "2022-09-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 12,
      profileName: "Microsoft Surface Pro 7",
      typeId: 3,
      notes: "Windows tablet with detachable keyboard.",
      purchasePrice: 1299.99,
      acquisitionDate: "2022-07-29 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 13,
      profileName: "Epson EcoTank L3150",
      typeId: 9,
      notes: "Wi-Fi All-in-One Ink Tank Printer.",
      purchasePrice: 299.99,
      acquisitionDate: "2022-06-10 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 14,
      profileName: "Logitech C920 HD Pro",
      typeId: 11,
      notes: "Webcam for HD video streaming.",
      purchasePrice: 99.99,
      acquisitionDate: "2022-04-25 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 15,
      profileName: "Netgear Nighthawk R7000",
      typeId: 7,
      notes: "Wi-Fi router for high-speed internet.",
      purchasePrice: 199.99,
      acquisitionDate: "2022-03-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 16,
      profileName: "Ubiquiti UniFi Switch",
      typeId: 7,
      notes: "Managed PoE+ Gigabit Switch with SFP.",
      purchasePrice: 299.99,
      acquisitionDate: "2022-01-28 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 17,
      profileName: "Dell PowerEdge T40",
      typeId: 8,
      notes: "Server tower with Intel Xeon processor.",
      purchasePrice: 999.99,
      acquisitionDate: "2021-12-05 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 18,
      profileName: "Yamaha DXR8",
      typeId: 10,
      notes: "Active loudspeaker for live sound reinforcement.",
      purchasePrice: 699.99,
      acquisitionDate: "2021-10-20 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 19,
      profileName: "Office Door Key",
      typeId: 13,
      notes: "A standard key for accessing office doors and general rooms.",
      purchasePrice: 19.99,
      acquisitionDate: "2021-08-30 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 20,
      profileName: "Server Room Key",
      typeId: 13,
      notes: "A high-security key for IT personnel to access server rooms.",
      purchasePrice: 29.99,
      acquisitionDate: "2021-07-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 21,
      profileName: "Master Key",
      typeId: 13,
      notes:
        "A universal key that provides access to multiple areas within the premises.",
      purchasePrice: 49.99,
      acquisitionDate: "2021-06-01 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 22,
      profileName: "Generic Landline Phone",
      typeId: 14,
      notes:
        "Standard wired telephone used for voice communication in homes and offices.",
      purchasePrice: 59.99,
      acquisitionDate: "2021-05-18 00:00:00",
      activeStatus: 0,
    },
    {
      profileId: 23,
      profileName: "Basic Fax Machine",
      typeId: 15,
      notes: "Device for sending and receiving documents over telephone lines.",
      purchasePrice: 199.99,
      acquisitionDate: "2021-04-04 00:00:00",
      activeStatus: 0,
    },
    {
      profileId: 24,
      profileName: "Smart Board",
      typeId: 16,
      notes:
        "Interactive whiteboard used for education and presentations, supporting touch and digital input.",
      purchasePrice: 999.99,
      acquisitionDate: "2021-03-20 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 25,
      profileName: "Epson PowerLite 1781W",
      typeId: 5,
      notes:
        "Portable, wireless WXGA projector, offering high-quality images and a slim, lightweight design.",
      purchasePrice: 799.99,
      acquisitionDate: "2021-02-05 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 26,
      profileName: "BenQ TK850",
      typeId: 5,
      notes:
        "4K HDR projector with high brightness, designed for well-lit rooms and home theaters.",
      purchasePrice: 1500.99,
      acquisitionDate: "2021-01-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 27,
      profileName: "Daikin Inverter HVAC",
      typeId: 4,
      notes: "Energy-efficient heating, ventilation, and air conditioning system.",
      purchasePrice: 3200.99,
      acquisitionDate: "2024-04-10 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 28,
      profileName: "Cisco Catalyst 9000",
      typeId: 6,
      notes: "Enterprise level network switch with advanced security features.",
      purchasePrice: 4500.00,
      acquisitionDate: "2024-03-15 00:00:00",
      activeStatus: 1,
    },
    {
      profileId: 29,
      profileName: "Shure SM7B",
      typeId: 10,
      notes: "Professional studio microphone for broadcasting and recording.",
      purchasePrice: 399.99,
      acquisitionDate: "2024-01-20 00:00:00",
      activeStatus: 1,
    },    
  ];

  try {
    await Promise.all(
      profiles.map((profile) => assetProfile.upsert({ ...profile }))
    );
    console.log("Asset Profiles initialized successfully");
  } catch (error) {
    console.log("Initialization failed:", error);
  }
}

module.exports = { initializeAssetProfile };
