const db = require("../models");
const log = db.log;

async function initializeLogs() {
  const logs = [
    {
      logId: 1,
      serializedAssetId: 1,
      notes: "Performed system software update and battery check.",
      serviceDate: "2024-03-19 00:00:00",
      performedBy: "John Doe",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 2,
      serializedAssetId: 1,
      notes: "Replaced cracked screen and tested touchscreen responsiveness.",
      serviceDate: "2023-08-12 00:00:00",
      performedBy: "Jane Smith",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 3,
      serializedAssetId: 2,
      notes: "Cleaned charging port and verified camera functionality.",
      serviceDate: "2023-04-25 00:00:00",
      performedBy: "Alice Johnson",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 4,
      serializedAssetId: 2,
      notes: "Updated to latest OS version and performed security check.",
      serviceDate: "2023-12-05 00:00:00",
      performedBy: "Bob White",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 5,
      serializedAssetId: 3,
      notes: "Battery replacement and general diagnostics.",
      serviceDate: "2023-07-30 00:00:00",
      performedBy: "Carlos Ray",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 6,
      serializedAssetId: 3,
      notes: "Checked Wi-Fi and Bluetooth connectivity issues.",
      serviceDate: "2023-02-17 00:00:00",
      performedBy: "Diana Prince",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 7,
      serializedAssetId: 4,
      notes: "Conducted full hardware check and cleaned internal components.",
      serviceDate: "2023-11-11 00:00:00",
      performedBy: "Ethan Hunt",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 8,
      serializedAssetId: 4,
      notes: "Replaced front and rear cameras and tested image quality.",
      serviceDate: "2023-09-21 00:00:00",
      performedBy: "Fiona Glenanne",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 9,
      serializedAssetId: 5,
      notes: "Upgraded RAM and tested system performance under load.",
      serviceDate: "2023-06-18 00:00:00",
      performedBy: "Gary Mason",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 10,
      serializedAssetId: 5,
      notes: "Performed disk cleanup and defragmentation.",
      serviceDate: "2023-10-10 00:00:00",
      performedBy: "Hannah Abbott",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 11,
      serializedAssetId: 6,
      notes: "Inspected motherboard for signs of wear and updated firmware.",
      serviceDate: "2023-05-23 00:00:00",
      performedBy: "Ivan Rogers",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 12,
      serializedAssetId: 6,
      notes: "Replaced faulty SSD and performed speed test.",
      serviceDate: "2023-01-29 00:00:00",
      performedBy: "Julia Espinosa",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 13,
      serializedAssetId: 7,
      notes: "Calibrated screen color profile and brightness settings.",
      serviceDate: "2023-03-15 00:00:00",
      performedBy: "Karl Jensen",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 14,
      serializedAssetId: 7,
      notes:
        "Cleaned keyboard and trackpad, checked all keys for responsiveness.",
      serviceDate: "2023-08-07 00:00:00",
      performedBy: "Linda Miles",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 15,
      serializedAssetId: 8,
      notes: "Checked wireless and LAN connectivity, updated network drivers.",
      serviceDate: "2023-02-20 00:00:00",
      performedBy: "Mike Lowell",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 16,
      serializedAssetId: 8,
      notes: "Inspected for physical damage and tested all ports.",
      serviceDate: "2023-11-12 00:00:00",
      performedBy: "Nina Pham",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 17,
      serializedAssetId: 9,
      notes: "Replaced aging battery, tested charge cycle.",
      serviceDate: "2023-07-22 00:00:00",
      performedBy: "Oscar Wallace",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 18,
      serializedAssetId: 9,
      notes: "Updated audio drivers and tested speaker output.",
      serviceDate: "2023-04-18 00:00:00",
      performedBy: "Patty Bell",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 19,
      serializedAssetId: 10,
      notes:
        "Installed latest operating system update, verified app compatibility.",
      serviceDate: "2023-09-27 00:00:00",
      performedBy: "Quentin Morales",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 20,
      serializedAssetId: 10,
      notes: "Performed annual maintenance check, including diagnostics run.",
      serviceDate: "2023-12-14 00:00:00",
      performedBy: "Rachel Diaz",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 21,
      serializedAssetId: 11,
      notes: "Checked and adjusted thermal management settings and fans.",
      serviceDate: "2023-03-05 00:00:00",
      performedBy: "Steve Franklin",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 22,
      serializedAssetId: 11,
      notes: "Upgraded hardware for improved graphics performance.",
      serviceDate: "2023-06-30 00:00:00",
      performedBy: "Tina Holloway",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 23,
      serializedAssetId: 12,
      notes: "Repaired loose hinge and verified laptop closure mechanism.",
      serviceDate: "2023-10-20 00:00:00",
      performedBy: "Umar Khan",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 24,
      serializedAssetId: 12,
      notes: "Tested all USB and HDMI ports for functionality.",
      serviceDate: "2023-01-16 00:00:00",
      performedBy: "Vicky Singh",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 25,
      serializedAssetId: 13,
      notes: "Replaced outdated RAM modules with upgraded ones.",
      serviceDate: "2023-05-28 00:00:00",
      performedBy: "William Grant",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 26,
      serializedAssetId: 13,
      notes: "Performed deep cleaning of internal fans and air vents.",
      serviceDate: "2023-08-09 00:00:00",
      performedBy: "Xavier Domingo",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 27,
      serializedAssetId: 14,
      notes: "Checked for BIOS updates and improved boot time settings.",
      serviceDate: "2023-02-19 00:00:00",
      performedBy: "Yasmin Chowdhury",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 28,
      serializedAssetId: 14,
      notes: "Updated all drivers, tested for stability with new software.",
      serviceDate: "2023-07-13 00:00:00",
      performedBy: "Zoe Carver",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 29,
      serializedAssetId: 15,
      notes: "Inspected and replaced damaged power supply unit.",
      serviceDate: "2023-01-24 00:00:00",
      performedBy: "Alan Turing",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 30,
      serializedAssetId: 15,
      notes: "Optimized storage management, cleared up unnecessary files.",
      serviceDate: "2023-10-18 00:00:00",
      performedBy: "Betty Ross",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 31,
      serializedAssetId: 16,
      notes: "Inspected and calibrated touch screen sensitivity.",
      serviceDate: "2023-06-27 00:00:00",
      performedBy: "John Doe",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 32,
      serializedAssetId: 16,
      notes: "Replaced main circuit board due to failure during operation.",
      serviceDate: "2023-05-22 00:00:00",
      performedBy: "Alice Johnson",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 33,
      serializedAssetId: 17,
      notes: "Updated firmware and conducted a security audit.",
      serviceDate: "2023-08-31 00:00:00",
      performedBy: "Bob White",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 34,
      serializedAssetId: 17,
      notes: "Cleaned internal components and replaced thermal paste.",
      serviceDate: "2023-11-17 00:00:00",
      performedBy: "Carlos Ray",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 35,
      serializedAssetId: 18,
      notes: "Performed routine maintenance and checked battery health.",
      serviceDate: "2023-02-12 00:00:00",
      performedBy: "Diana Prince",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 36,
      serializedAssetId: 18,
      notes:
        "Checked and adjusted the display settings for optimal performance.",
      serviceDate: "2023-05-29 00:00:00",
      performedBy: "Ethan Hunt",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 37,
      serializedAssetId: 19,
      notes: "Tested all communication ports and updated network settings.",
      serviceDate: "2023-09-24 00:00:00",
      performedBy: "Fiona Glenanne",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 38,
      serializedAssetId: 19,
      notes: "Replaced speakers and tested audio output quality.",
      serviceDate: "2023-12-19 00:00:00",
      performedBy: "Gary Mason",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 39,
      serializedAssetId: 20,
      notes: "Updated operating system and removed outdated software.",
      serviceDate: "2023-04-26 00:00:00",
      performedBy: "Hannah Abbott",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 40,
      serializedAssetId: 20,
      notes: "Inspected hardware for signs of physical wear and stress.",
      serviceDate: "2023-07-15 00:00:00",
      performedBy: "Ivan Rogers",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 41,
      serializedAssetId: 21,
      notes: "Performed deep system diagnostics and resolved boot issues.",
      serviceDate: "2023-01-21 00:00:00",
      performedBy: "Julia Espinosa",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 42,
      serializedAssetId: 21,
      notes: "Replaced keyboard and mouse due to wear and tear.",
      serviceDate: "2023-06-11 00:00:00",
      performedBy: "Karl Jensen",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 43,
      serializedAssetId: 22,
      notes:
        "Conducted full virus scan and installed latest antivirus software.",
      serviceDate: "2023-12-29 00:00:00",
      performedBy: "Linda Miles",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 44,
      serializedAssetId: 22,
      notes:
        "Upgraded graphics card and tested for compatibility with new software.",
      serviceDate: "2023-11-23 00:00:00",
      performedBy: "Mike Lowell",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 45,
      serializedAssetId: 23,
      notes: "Tested webcam functionality and updated drivers.",
      serviceDate: "2023-05-31 00:00:00",
      performedBy: "Nina Pham",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 46,
      serializedAssetId: 23,
      notes: "Checked all input/output devices for proper functioning.",
      serviceDate: "2023-06-26 00:00:00",
      performedBy: "Oscar Wallace",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 47,
      serializedAssetId: 24,
      notes: "Replaced power supply unit and checked voltage stability.",
      serviceDate: "2023-07-29 00:00:00",
      performedBy: "Patty Bell",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 48,
      serializedAssetId: 24,
      notes:
        "Conducted a detailed cleaning of all external and internal components.",
      serviceDate: "2023-10-22 00:00:00",
      performedBy: "Quentin Morales",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 49,
      serializedAssetId: 25,
      notes:
        "Updated communication software and improved connection stability.",
      serviceDate: "2023-01-17 00:00:00",
      performedBy: "Rachel Diaz",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 50,
      serializedAssetId: 25,
      notes: "Replaced aging hard drive with a faster SSD, cloned data.",
      serviceDate: "2023-04-24 00:00:00",
      performedBy: "Steve Franklin",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 51,
      serializedAssetId: 26,
      notes:
        "Upgraded to higher capacity battery, tested new battery lifecycle.",
      serviceDate: "2023-08-31 00:00:00",
      performedBy: "Tina Holloway",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 52,
      serializedAssetId: 26,
      notes: "Performed a comprehensive cleaning of all vents and filters.",
      serviceDate: "2023-11-14 00:00:00",
      performedBy: "Umar Khan",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 53,
      serializedAssetId: 27,
      notes: "Updated operating system and optimized storage settings.",
      serviceDate: "2023-03-31 00:00:00",
      performedBy: "Vicky Singh",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 54,
      serializedAssetId: 27,
      notes:
        "Replaced the touchscreen digitizer and tested for responsiveness.",
      serviceDate: "2023-06-20 00:00:00",
      performedBy: "William Grant",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 55,
      serializedAssetId: 28,
      notes: "Conducted security checks and updated firewall settings.",
      serviceDate: "2023-12-27 00:00:00",
      performedBy: "Xavier Domingo",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 56,
      serializedAssetId: 28,
      notes: "Updated video drivers and tested display performance.",
      serviceDate: "2023-05-17 00:00:00",
      performedBy: "Yasmin Chowdhury",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 57,
      serializedAssetId: 29,
      notes: "Checked system memory and upgraded to faster modules.",
      serviceDate: "2023-11-30 00:00:00",
      performedBy: "Zoe Carver",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 58,
      serializedAssetId: 29,
      notes: "Inspected motherboard and replaced faulty capacitors.",
      serviceDate: "2023-10-26 00:00:00",
      performedBy: "Alan Turing",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 59,
      serializedAssetId: 30,
      notes: "Calibrated battery and performed end-to-end system diagnostics.",
      serviceDate: "2023-04-29 00:00:00",
      performedBy: "Betty Ross",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 60,
      serializedAssetId: 30,
      notes: "Updated network card drivers and tested connectivity.",
      serviceDate: "2023-07-24 00:00:00",
      performedBy: "John Doe",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 61,
      serializedAssetId: 31,
      notes:
        "Replaced aging graphics card with new model, tested with heavy graphics use.",
      serviceDate: "2023-06-22 00:00:00",
      performedBy: "Jane Smith",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 62,
      serializedAssetId: 31,
      notes:
        "Conducted a deep clean of all hardware components, checked for dust and debris.",
      serviceDate: "2023-09-27 00:00:00",
      performedBy: "Alice Johnson",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 63,
      serializedAssetId: 32,
      notes:
        "Updated security protocols and reinforced data protection measures.",
      serviceDate: "2023-12-20 00:00:00",
      performedBy: "Bob White",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 64,
      serializedAssetId: 32,
      notes: "Checked cooling system and replaced malfunctioning fans.",
      serviceDate: "2023-03-18 00:00:00",
      performedBy: "Carlos Ray",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 65,
      serializedAssetId: 33,
      notes: "Performed system recovery and data backup procedures.",
      serviceDate: "2023-07-28 00:00:00",
      performedBy: "Diana Prince",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 66,
      serializedAssetId: 33,
      notes: "Replaced defective USB ports and tested for functionality.",
      serviceDate: "2023-10-10 00:00:00",
      performedBy: "Ethan Hunt",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 67,
      serializedAssetId: 34,
      notes:
        "Installed latest software updates and patched known vulnerabilities.",
      serviceDate: "2023-02-25 00:00:00",
      performedBy: "Fiona Glenanne",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 68,
      serializedAssetId: 34,
      notes: "Tested and calibrated new input devices (keyboard, mouse).",
      serviceDate: "2023-05-14 00:00:00",
      performedBy: "Gary Mason",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 69,
      serializedAssetId: 35,
      notes:
        "Upgraded power management settings and checked for optimal energy usage.",
      serviceDate: "2023-11-22 00:00:00",
      performedBy: "Hannah Abbott",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 70,
      serializedAssetId: 35,
      notes: "Cleaned and tested all audio and video interfaces for faults.",
      serviceDate: "2023-04-13 00:00:00",
      performedBy: "Ivan Rogers",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 71,
      serializedAssetId: 36,
      notes: "Replaced battery and tested new unit for optimal performance.",
      serviceDate: "2023-10-31 00:00:00",
      performedBy: "Julia Espinosa",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 72,
      serializedAssetId: 36,
      notes: "Conducted full system virus scan and installed security updates.",
      serviceDate: "2023-09-29 00:00:00",
      performedBy: "Karl Jensen",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 73,
      serializedAssetId: 37,
      notes: "Inspected and repaired hardware interfaces and connectors.",
      serviceDate: "2023-03-31 00:00:00",
      performedBy: "Linda Miles",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 74,
      serializedAssetId: 37,
      notes: "Updated all drivers and software to latest versions.",
      serviceDate: "2023-08-21 00:00:00",
      performedBy: "Mike Lowell",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 75,
      serializedAssetId: 38,
      notes:
        "Performed cleaning of internal circuits and checked electrical flow.",
      serviceDate: "2023-05-25 00:00:00",
      performedBy: "Nina Pham",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 76,
      serializedAssetId: 38,
      notes: "Replaced the hard drive with an SSD and migrated data.",
      serviceDate: "2023-08-30 00:00:00",
      performedBy: "Oscar Wallace",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 77,
      serializedAssetId: 39,
      notes: "Upgraded system memory and tested for faults under stress.",
      serviceDate: "2023-11-26 00:00:00",
      performedBy: "Patty Bell",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 78,
      serializedAssetId: 39,
      notes: "Inspected all networking equipment and updated configurations.",
      serviceDate: "2023-02-12 00:00:00",
      performedBy: "Quentin Morales",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 79,
      serializedAssetId: 40,
      notes: "Calibrated display settings and checked for color accuracy.",
      serviceDate: "2023-06-25 00:00:00",
      performedBy: "Rachel Diaz",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 80,
      serializedAssetId: 40,
      notes: "Performed comprehensive system diagnostics and troubleshooting.",
      serviceDate: "2023-09-05 00:00:00",
      performedBy: "Steve Franklin",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 81,
      serializedAssetId: 41,
      notes:
        "Replaced thermal management components and tested cooling efficiency.",
      serviceDate: "2023-01-27 00:00:00",
      performedBy: "Tina Holloway",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 82,
      serializedAssetId: 41,
      notes: "Updated BIOS and performed a motherboard stress test.",
      serviceDate: "2023-04-16 00:00:00",
      performedBy: "Umar Khan",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 83,
      serializedAssetId: 42,
      notes: "Checked and secured all internal connections and cables.",
      serviceDate: "2023-10-25 00:00:00",
      performedBy: "Vicky Singh",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 84,
      serializedAssetId: 42,
      notes: "Repaired and replaced faulty RAM slots and memory modules.",
      serviceDate: "2023-03-09 00:00:00",
      performedBy: "William Grant",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 85,
      serializedAssetId: 43,
      notes: "Upgraded video card and tested for high-resolution output.",
      serviceDate: "2023-09-28 00:00:00",
      performedBy: "Xavier Domingo",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 86,
      serializedAssetId: 43,
      notes: "Checked software licenses and compliance with updates.",
      serviceDate: "2023-08-25 00:00:00",
      performedBy: "Yasmin Chowdhury",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 87,
      serializedAssetId: 44,
      notes: "Replaced projector lamp and calibrated projector settings.",
      serviceDate: "2023-02-29 00:00:00",
      performedBy: "Zoe Carver",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 88,
      serializedAssetId: 44,
      notes: "Performed alignment and calibration of audio equipment.",
      serviceDate: "2023-09-18 00:00:00",
      performedBy: "Alan Turing",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 89,
      serializedAssetId: 45,
      notes: "Updated networking firmware and tested wireless signal strength.",
      serviceDate: "2023-04-20 00:00:00",
      performedBy: "Betty Ross",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 90,
      serializedAssetId: 45,
      notes:
        "Replaced worn-out scanner components and tested for operational efficiency.",
      serviceDate: "2023-07-26 00:00:00",
      performedBy: "John Doe",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 91,
      serializedAssetId: 46,
      notes: "Conducted electrical safety checks and grounding of equipment.",
      serviceDate: "2023-10-24 00:00:00",
      performedBy: "Jane Smith",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 92,
      serializedAssetId: 46,
      notes:
        "Installed new security software and verified data encryption protocols.",
      serviceDate: "2023-01-14 00:00:00",
      performedBy: "Alice Johnson",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 93,
      serializedAssetId: 47,
      notes:
        "Updated operating system and optimized system settings for better performance.",
      serviceDate: "2023-05-27 00:00:00",
      performedBy: "Bob White",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 94,
      serializedAssetId: 47,
      notes:
        "Cleaned internal fans and checked for operational efficiency under load.",
      serviceDate: "2023-08-07 00:00:00",
      performedBy: "Carlos Ray",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 95,
      serializedAssetId: 48,
      notes:
        "Replaced all worn keys on keyboards and tested for responsiveness.",
      serviceDate: "2023-12-29 00:00:00",
      performedBy: "Diana Prince",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 96,
      serializedAssetId: 48,
      notes: "Upgraded CPU and tested system performance enhancements.",
      serviceDate: "2023-03-12 00:00:00",
      performedBy: "Ethan Hunt",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 97,
      serializedAssetId: 49,
      notes: "Checked and replaced faulty network switches.",
      serviceDate: "2023-09-20 00:00:00",
      performedBy: "Fiona Glenanne",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 98,
      serializedAssetId: 49,
      notes: "Performed data recovery operations and ensured data integrity.",
      serviceDate: "2023-02-10 00:00:00",
      performedBy: "Gary Mason",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 99,
      serializedAssetId: 50,
      notes: "Updated web server configurations and tested for load handling.",
      serviceDate: "2023-08-24 00:00:00",
      performedBy: "Hannah Abbott",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 100,
      serializedAssetId: 50,
      notes: "Replaced and tested faulty power units within the system.",
      serviceDate: "2023-07-28 00:00:00",
      performedBy: "Ivan Rogers",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 101,
      serializedAssetId: 51,
      notes: "Replaced aging battery and tested for charging efficiency.",
      serviceDate: "2023-01-27 00:00:00",
      performedBy: "Julia Espinosa",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 102,
      serializedAssetId: 51,
      notes: "Calibrated all input devices and updated drivers.",
      serviceDate: "2023-10-16 00:00:00",
      performedBy: "Karl Jensen",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 103,
      serializedAssetId: 52,
      notes:
        "Performed full hardware diagnostics and replaced faulty memory modules.",
      serviceDate: "2023-03-16 00:00:00",
      performedBy: "Linda Miles",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 104,
      serializedAssetId: 52,
      notes:
        "Updated system to the latest OS version and optimized performance settings.",
      serviceDate: "2023-06-29 00:00:00",
      performedBy: "Mike Lowell",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 105,
      serializedAssetId: 53,
      notes:
        "Repaired and replaced the network card, tested for connectivity issues.",
      serviceDate: "2023-09-19 00:00:00",
      performedBy: "Nina Pham",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 106,
      serializedAssetId: 53,
      notes: "Checked security systems and updated firewall configurations.",
      serviceDate: "2023-12-09 00:00:00",
      performedBy: "Oscar Wallace",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 107,
      serializedAssetId: 54,
      notes:
        "Replaced cooling system components and tested under high-load conditions.",
      serviceDate: "2023-04-22 00:00:00",
      performedBy: "Patty Bell",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 108,
      serializedAssetId: 54,
      notes:
        "Upgraded storage devices and performed data migration and verification.",
      serviceDate: "2023-07-03 00:00:00",
      performedBy: "Quentin Morales",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 109,
      serializedAssetId: 55,
      notes:
        "Conducted electrical safety inspection and replaced non-compliant components.",
      serviceDate: "2023-11-24 00:00:00",
      performedBy: "Rachel Diaz",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 110,
      serializedAssetId: 55,
      notes:
        "Updated network security protocols and tested for vulnerabilities.",
      serviceDate: "2023-02-05 00:00:00",
      performedBy: "Steve Franklin",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 111,
      serializedAssetId: 56,
      notes:
        "Checked and repaired peripheral device connections and interfaces.",
      serviceDate: "2023-08-23 00:00:00",
      performedBy: "Tina Holloway",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 112,
      serializedAssetId: 56,
      notes: "Performed software reinstallation and system optimization.",
      serviceDate: "2023-01-06 00:00:00",
      performedBy: "Umar Khan",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 113,
      serializedAssetId: 57,
      notes:
        "Replaced projector bulbs and adjusted image settings for optimal clarity.",
      serviceDate: "2023-07-27 00:00:00",
      performedBy: "Vicky Singh",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 114,
      serializedAssetId: 57,
      notes:
        "Upgraded firmware on all connected devices and tested interoperability.",
      serviceDate: "2023-06-30 00:00:00",
      performedBy: "William Grant",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 115,
      serializedAssetId: 58,
      notes:
        "Replaced aging routers and switches, tested network throughput and stability.",
      serviceDate: "2023-12-28 00:00:00",
      performedBy: "Xavier Domingo",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 116,
      serializedAssetId: 58,
      notes:
        "Cleaned and tested all output devices for audio and video functions.",
      serviceDate: "2023-11-13 00:00:00",
      performedBy: "Yasmin Chowdhury",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 117,
      serializedAssetId: 59,
      notes:
        "Updated antivirus and anti-malware software, ran a full system scan.",
      serviceDate: "2023-02-09 00:00:00",
      performedBy: "Zoe Carver",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 118,
      serializedAssetId: 59,
      notes: "Inspected and replaced worn cables and connectors.",
      serviceDate: "2023-05-31 00:00:00",
      performedBy: "Alan Turing",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 119,
      serializedAssetId: 60,
      notes:
        "Performed color calibration on monitors and updated graphics settings.",
      serviceDate: "2023-08-22 00:00:00",
      performedBy: "Betty Ross",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 120,
      serializedAssetId: 60,
      notes:
        "Replaced and upgraded the central processing unit (CPU), tested system speeds.",
      serviceDate: "2023-11-04 00:00:00",
      performedBy: "John Doe",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 121,
      serializedAssetId: 61,
      notes:
        "Upgraded the operating system and installed new security patches.",
      serviceDate: "2023-03-25 00:00:00",
      performedBy: "Jane Smith",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 122,
      serializedAssetId: 61,
      notes: "Cleaned internal components and checked for any physical damage.",
      serviceDate: "2023-05-29 00:00:00",
      performedBy: "Alice Johnson",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 123,
      serializedAssetId: 62,
      notes: "Replaced damaged screen and tested touchscreen functionality.",
      serviceDate: "2023-10-27 00:00:00",
      performedBy: "Bob White",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 124,
      serializedAssetId: 62,
      notes:
        "Updated all multimedia software and tested for user compatibility.",
      serviceDate: "2023-01-08 00:00:00",
      performedBy: "Carlos Ray",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 125,
      serializedAssetId: 63,
      notes: "Performed data integrity checks and restored data from backup.",
      serviceDate: "2023-07-26 00:00:00",
      performedBy: "Diana Prince",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 126,
      serializedAssetId: 63,
      notes:
        "Installed new network monitoring tools and configured alerts for system events.",
      serviceDate: "2023-12-01 00:00:00",
      performedBy: "Ethan Hunt",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 127,
      serializedAssetId: 64,
      notes:
        "Replaced end-of-life hardware with upgraded models, tested to ensure compliance.",
      serviceDate: "2023-06-29 00:00:00",
      performedBy: "Fiona Glenanne",
      isPreventative: false,
      isRepair: false,
      isUpgrade: true,
    },
    {
      logId: 128,
      serializedAssetId: 64,
      notes:
        "Checked for electrical faults and replaced defective power supplies.",
      serviceDate: "2023-05-31 00:00:00",
      performedBy: "Gary Mason",
      isPreventative: false,
      isRepair: true,
      isUpgrade: false,
    },
    {
      logId: 129,
      serializedAssetId: 65,
      notes:
        "Updated server firmware and optimized server settings for increased efficiency.",
      serviceDate: "2023-11-30 00:00:00",
      performedBy: "Hannah Abbott",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
    {
      logId: 130,
      serializedAssetId: 65,
      notes: "Inspected security systems and upgraded surveillance software.",
      serviceDate: "2023-12-11 00:00:00",
      performedBy: "Ivan Rogers",
      isPreventative: true,
      isRepair: false,
      isUpgrade: false,
    },
  ];

  try {
    await Promise.all(logs.map((logInst) => log.upsert({ ...logInst })));
    console.log("Logs initialized successfully for all serialized assets'.");
  } catch (error) {
    console.log("Initialization failed:", error);
  }
}

module.exports = { initializeLogs };
