const db = require("../models");
const Person = db.person;

async function initializePersons() {
  try {
    await Promise.all([
      Person.upsert({
        personId: 1,
        fName: "Jaxen",
        lName: "McRay",
        email: "jaxen.mcray@eagles.oc.edu",
        idNumber: "1000001",
      }),
      Person.upsert({
        personId: 2,
        fName: "Zane",
        lName: "Fike",
        email: "z.fike@eagles.oc.edu",
        idNumber: "1000002",
      }),
      Person.upsert({
        personId: 3,
        fName: "Solomon",
        lName: "Granger",
        email: "solomon.granger@eagles.oc.edu",
        idNumber: "1000003",
      }),
      Person.upsert({
        personId: 4,
        fName: "Justin",
        lName: "Davis",
        email: "justin.davis@eagles.oc.edu",
        idNumber: "1000004",
      }),
      Person.upsert({
        personId: 5,
        fName: "Emily",
        lName: "Wong",
        email: "emily.wong@eagles.oc.edu",
        idNumber: "1000005",
      }),
      Person.upsert({
        personId: 6,
        fName: "Garrett-Peter",
        lName: "Thompson",
        email: "gp.thompson@eagles.oc.edu",
        idNumber: "1000006",
      }),
      Person.upsert({
        personId: 7,
        fName: "Arthur",
        lName: "Morgan",
        email: "arthur.morgan@eagles.oc.edu",
        idNumber: "1000007",
      }),
      Person.upsert({
        personId: 8,
        fName: "Lucas",
        lName: "Morris",
        email: "lucas.morris@eagles.oc.edu",
        idNumber: "1000008",
      }),
      Person.upsert({
        personId: 9,
        fName: "Sophia",
        lName: "Garcia",
        email: "sophia.garcia@eagles.oc.edu",
        idNumber: "1000009",
      }),
      Person.upsert({
        personId: 10,
        fName: "Ethan",
        lName: "Lee",
        email: "ethan.lee@eagles.oc.edu",
        idNumber: "1000010",
      }),
      Person.upsert({
        personId: 11,
        fName: "Alex",
        lName: "Johnson",
        email: "alex.johnson@eagles.oc.edu",
        idNumber: "1000011",
      }),
      Person.upsert({
        personId: 12,
        fName: "Isabella",
        lName: "Martinez",
        email: "isabella.martinez@eagles.oc.edu",
        idNumber: "1000012",
      }),
      Person.upsert({
        personId: 13,
        fName: "Elijah",
        lName: "Hernandez",
        email: "elijah.hernandez@eagles.oc.edu",
        idNumber: "1000013",
      }),
      Person.upsert({
        personId: 14,
        fName: "Zoe",
        lName: "Robinson",
        email: "zoe.robinson@eagles.oc.edu",
        idNumber: "1000014",
      }),
      Person.upsert({
        personId: 15,
        fName: "Adrian",
        lName: "Clark",
        email: "adrian.clark@eagles.oc.edu",
        idNumber: "1000015",
      }),
      Person.upsert({
        personId: 16,
        fName: "Samantha",
        lName: "Lewis",
        email: "samantha.lewis@eagles.oc.edu",
        idNumber: "1000016",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 17,
        fName: "Ian",
        lName: "Walker",
        email: "ian.walker@eagles.oc.edu",
        idNumber: "1000017",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 18,
        fName: "Julia",
        lName: "Perez",
        email: "julia.perez@eagles.oc.edu",
        idNumber: "1000018",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 19,
        fName: "Mia",
        lName: "Ramirez",
        email: "mia.ramirez@eagles.oc.edu",
        idNumber: "1000019",
      }),
      Person.upsert({
        personId: 20,
        fName: "Mason",
        lName: "Bennett",
        email: "mason.bennett@eagles.oc.edu",
        idNumber: "1000020",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 21,
        fName: "Chloe",
        lName: "Hughes",
        email: "chloe.hughes@eagles.oc.edu",
        idNumber: "1000021",
      }),
      Person.upsert({
        personId: 22,
        fName: "Logan",
        lName: "Moore",
        email: "logan.moore@eagles.oc.edu",
        idNumber: "1000022",
      }),
      Person.upsert({
        personId: 23,
        fName: "Ava",
        lName: "Foster",
        email: "ava.foster@eagles.oc.edu",
        idNumber: "1000023",
      }),
      Person.upsert({
        personId: 24,
        fName: "Jacob",
        lName: "Howard",
        email: "jacob.howard@eagles.oc.edu",
        idNumber: "1000024",
      }),
      Person.upsert({
        personId: 25,
        fName: "Madison",
        lName: "Edwards",
        email: "madison.edwards@eagles.oc.edu",
        idNumber: "1000025",
      }),
      Person.upsert({
        personId: 26,
        fName: "Oliver",
        lName: "Cox",
        email: "oliver.cox@eagles.oc.edu",
        idNumber: "1000026",
      }),
      Person.upsert({
        personId: 27,
        fName: "Sophie",
        lName: "Shaw",
        email: "sophie.shaw@eagles.oc.edu",
        idNumber: "1000027",
      }),
      Person.upsert({
        personId: 28,
        fName: "Owen",
        lName: "Holmes",
        email: "owen.holmes@eagles.oc.edu",
        idNumber: "1000028",
      }),
      Person.upsert({
        personId: 29,
        fName: "Lily",
        lName: "Rice",
        email: "lily.rice@eagles.oc.edu",
        idNumber: "1000029",
      }),
      Person.upsert({
        personId: 30,
        fName: "Carter",
        lName: "Jenkins",
        email: "carter.jenkins@eagles.oc.edu",
        idNumber: "1000030",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 31,
        fName: "Ella",
        lName: "Perry",
        email: "ella.perry@eagles.oc.edu",
        idNumber: "1000031",
      }),
      Person.upsert({
        personId: 32,
        fName: "Jack",
        lName: "Powell",
        email: "jack.powell@eagles.oc.edu",
        idNumber: "1000032",
      }),
      Person.upsert({
        personId: 33,
        fName: "Grace",
        lName: "Long",
        email: "grace.long@eagles.oc.edu",
        idNumber: "1000033",
      }),
      Person.upsert({
        personId: 34,
        fName: "Liam",
        lName: "Patterson",
        email: "liam.patterson@eagles.oc.edu",
        idNumber: "1000034",
      }),
      Person.upsert({
        personId: 35,
        fName: "Zoe",
        lName: "Ross",
        email: "zoe.ross@eagles.oc.edu",
        idNumber: "1000035",
      }),
      Person.upsert({
        personId: 36,
        fName: "Lucas",
        lName: "Walsh",
        email: "lucas.walsh@eagles.oc.edu",
        idNumber: "1000036",
      }),
      Person.upsert({
        personId: 37,
        fName: "Natalie",
        lName: "Arnold",
        email: "natalie.arnold@eagles.oc.edu",
        idNumber: "1000037",
      }),
      Person.upsert({
        personId: 38,
        fName: "Gabriel",
        lName: "Burke",
        email: "gabriel.burke@eagles.oc.edu",
        idNumber: "1000038",
      }),
      Person.upsert({
        personId: 39,
        fName: "Emily",
        lName: "Harper",
        email: "emily.harper@eagles.oc.edu",
        idNumber: "1000039",
      }),
      Person.upsert({
        personId: 40,
        fName: "Ethan",
        lName: "Fox",
        email: "ethan.fox@eagles.oc.edu",
        idNumber: "1000040",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 41,
        fName: "Isabella",
        lName: "West",
        email: "isabella.west@eagles.oc.edu",
        idNumber: "1000041",
      }),
      Person.upsert({
        personId: 42,
        fName: "Michael",
        lName: "Jordan",
        email: "michael.jordan@eagles.oc.edu",
        idNumber: "1000042",
      }),
      Person.upsert({
        personId: 43,
        fName: "Abigail",
        lName: "Cole",
        email: "abigail.cole@eagles.oc.edu",
        idNumber: "1000043",
      }),
      Person.upsert({
        personId: 44,
        fName: "Noah",
        lName: "Ellis",
        email: "noah.ellis@eagles.oc.edu",
        idNumber: "1000044",
      }),
      Person.upsert({
        personId: 45,
        fName: "Emma",
        lName: "Harrison",
        email: "emma.harrison@eagles.oc.edu",
        idNumber: "1000045",
      }),
      Person.upsert({
        personId: 46,
        fName: "Oliver",
        lName: "Gibson",
        email: "oliver.gibson@eagles.oc.edu",
        idNumber: "1000046",
      }),
      Person.upsert({
        personId: 47,
        fName: "Ava",
        lName: "McDonald",
        email: "ava.mcdonald@eagles.oc.edu",
        idNumber: "1000047",
      }),
      Person.upsert({
        personId: 48,
        fName: "Liam",
        lName: "Cruz",
        email: "liam.cruz@eagles.oc.edu",
        idNumber: "1000048",
      }),
      Person.upsert({
        personId: 49,
        fName: "Sophia",
        lName: "Marshall",
        email: "sophia.marshall@eagles.oc.edu",
        idNumber: "1000049",
      }),
      Person.upsert({
        personId: 50,
        fName: "Jacob",
        lName: "Ortiz",
        email: "jacob.ortiz@eagles.oc.edu",
        idNumber: "1000050",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 51,
        fName: "Mia",
        lName: "Gomez",
        email: "mia.gomez@eagles.oc.edu",
        idNumber: "1000051",
      }),
      Person.upsert({
        personId: 52,
        fName: "William",
        lName: "Murray",
        email: "william.murray@eagles.oc.edu",
        idNumber: "1000052",
      }),
      Person.upsert({
        personId: 53,
        fName: "Madison",
        lName: "Freeman",
        email: "madison.freeman@eagles.oc.edu",
        idNumber: "1000053",
      }),
      Person.upsert({
        personId: 54,
        fName: "James",
        lName: "Wells",
        email: "james.wells@eagles.oc.edu",
        idNumber: "1000054",
      }),
      Person.upsert({
        personId: 55,
        fName: "Amelia",
        lName: "Webb",
        email: "amelia.webb@eagles.oc.edu",
        idNumber: "1000055",
      }),
      Person.upsert({
        personId: 56,
        fName: "Benjamin",
        lName: "Simpson",
        email: "benjamin.simpson@eagles.oc.edu",
        idNumber: "1000056",
      }),
      Person.upsert({
        personId: 57,
        fName: "Emily",
        lName: "Stevens",
        email: "emily.stevens@eagles.oc.edu",
        idNumber: "1000057",
      }),
      Person.upsert({
        personId: 58,
        fName: "Alexander",
        lName: "Tucker",
        email: "alexander.tucker@eagles.oc.edu",
        idNumber: "1000058",
      }),
      Person.upsert({
        personId: 59,
        fName: "Charlotte",
        lName: "Porter",
        email: "charlotte.porter@eagles.oc.edu",
        idNumber: "1000059",
      }),
      Person.upsert({
        personId: 60,
        fName: "Olivia",
        lName: "Hunter",
        email: "olivia.hunter@eagles.oc.edu",
        idNumber: "1000060",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 61,
        fName: "Henry",
        lName: "Andrews",
        email: "henry.andrews@eagles.oc.edu",
        idNumber: "1000061",
      }),
      Person.upsert({
        personId: 62,
        fName: "Zoe",
        lName: "Ray",
        email: "zoe.ray@eagles.oc.edu",
        idNumber: "1000062",
      }),
      Person.upsert({
        personId: 63,
        fName: "Aiden",
        lName: "Soto",
        email: "aiden.soto@eagles.oc.edu",
        idNumber: "1000063",
      }),
      Person.upsert({
        personId: 64,
        fName: "Layla",
        lName: "Reynolds",
        email: "layla.reynolds@eagles.oc.edu",
        idNumber: "1000064",
      }),
      Person.upsert({
        personId: 65,
        fName: "Matthew",
        lName: "Burns",
        email: "matthew.burns@eagles.oc.edu",
        idNumber: "1000065",
      }),
      Person.upsert({
        personId: 66,
        fName: "Scarlett",
        lName: "Gordon",
        email: "scarlett.gordon@eagles.oc.edu",
        idNumber: "1000066",
      }),
      Person.upsert({
        personId: 67,
        fName: "Jack",
        lName: "Shaw",
        email: "jack.shaw@eagles.oc.edu",
        idNumber: "1000067",
      }),
      Person.upsert({
        personId: 68,
        fName: "Avery",
        lName: "Lane",
        email: "avery.lane@eagles.oc.edu",
        idNumber: "1000068",
      }),
      Person.upsert({
        personId: 69,
        fName: "Isabelle",
        lName: "Riley",
        email: "isabelle.riley@eagles.oc.edu",
        idNumber: "1000069",
      }),
      Person.upsert({
        personId: 70,
        fName: "Lucas",
        lName: "Carpenter",
        email: "lucas.carpenter@eagles.oc.edu",
        idNumber: "1000070",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 71,
        fName: "Evelyn",
        lName: "Wheeler",
        email: "evelyn.wheeler@eagles.oc.edu",
        idNumber: "1000071",
      }),
      Person.upsert({
        personId: 72,
        fName: "Gabriel",
        lName: "Pearson",
        email: "gabriel.pearson@eagles.oc.edu",
        idNumber: "1000072",
      }),
      Person.upsert({
        personId: 73,
        fName: "Lily",
        lName: "Morales",
        email: "lily.morales@eagles.oc.edu",
        idNumber: "1000073",
      }),
      Person.upsert({
        personId: 74,
        fName: "Elijah",
        lName: "Cook",
        email: "elijah.cook@eagles.oc.edu",
        idNumber: "1000074",
      }),
      Person.upsert({
        personId: 75,
        fName: "Sofia",
        lName: "Bailey",
        email: "sofia.bailey@eagles.oc.edu",
        idNumber: "1000075",
      }),
      Person.upsert({
        personId: 76,
        fName: "Mason",
        lName: "Rivera",
        email: "mason.rivera@eagles.oc.edu",
        idNumber: "1000076",
      }),
      Person.upsert({
        personId: 77,
        fName: "Camila",
        lName: "Dunn",
        email: "camila.dunn@eagles.oc.edu",
        idNumber: "1000077",
      }),
      Person.upsert({
        personId: 78,
        fName: "Dylan",
        lName: "Bradley",
        email: "dylan.bradley@eagles.oc.edu",
        idNumber: "1000078",
      }),
      Person.upsert({
        personId: 79,
        fName: "Madelyn",
        lName: "Daniels",
        email: "madelyn.daniels@eagles.oc.edu",
        idNumber: "1000079",
      }),
      Person.upsert({
        personId: 80,
        fName: "Charlotte",
        lName: "Weber",
        email: "charlotte.weber@eagles.oc.edu",
        idNumber: "1000080",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 81,
        fName: "Ryan",
        lName: "Nichols",
        email: "ryan.nichols@eagles.oc.edu",
        idNumber: "1000081",
      }),
      Person.upsert({
        personId: 82,
        fName: "Leah",
        lName: "Griffith",
        email: "leah.griffith@eagles.oc.edu",
        idNumber: "1000082",
      }),
      Person.upsert({
        personId: 83,
        fName: "Carter",
        lName: "Stone",
        email: "carter.stone@eagles.oc.edu",
        idNumber: "1000083",
      }),
      Person.upsert({
        personId: 84,
        fName: "Nora",
        lName: "Sullivan",
        email: "nora.sullivan@eagles.oc.edu",
        idNumber: "1000084",
      }),
      Person.upsert({
        personId: 85,
        fName: "Luke",
        lName: "Russell",
        email: "luke.russell@eagles.oc.edu",
        idNumber: "1000085",
      }),
      Person.upsert({
        personId: 86,
        fName: "Zoey",
        lName: "Pearce",
        email: "zoey.pearce@eagles.oc.edu",
        idNumber: "1000086",
      }),
      Person.upsert({
        personId: 87,
        fName: "Adam",
        lName: "Baxter",
        email: "adam.baxter@eagles.oc.edu",
        idNumber: "1000087",
      }),
      Person.upsert({
        personId: 88,
        fName: "Lily",
        lName: "Alexander",
        email: "lily.alexander@eagles.oc.edu",
        idNumber: "1000088",
      }),
      Person.upsert({
        personId: 89,
        fName: "Grace",
        lName: "Morris",
        email: "grace.morris@eagles.oc.edu",
        idNumber: "1000089",
      }),
      Person.upsert({
        personId: 90,
        fName: "Jackson",
        lName: "Atkins",
        email: "jackson.atkins@eagles.oc.edu",
        idNumber: "1000090",
        activeStatus: 0,
      }),
      Person.upsert({
        personId: 91,
        fName: "Aubrey",
        lName: "Wright",
        email: "aubrey.wright@eagles.oc.edu",
        idNumber: "1000091",
      }),
      Person.upsert({
        personId: 92,
        fName: "Henry",
        lName: "Fisher",
        email: "henry.fisher@eagles.oc.edu",
        idNumber: "1000092",
      }),
      Person.upsert({
        personId: 93,
        fName: "Eva",
        lName: "Cunningham",
        email: "eva.cunningham@eagles.oc.edu",
        idNumber: "1000093",
      }),
      Person.upsert({
        personId: 94,
        fName: "Oliver",
        lName: "Rhodes",
        email: "oliver.rhodes@eagles.oc.edu",
        idNumber: "1000094",
      }),
      Person.upsert({
        personId: 95,
        fName: "Anna",
        lName: "Ellis",
        email: "anna.ellis@eagles.oc.edu",
        idNumber: "1000095",
      }),
      Person.upsert({
        personId: 96,
        fName: "Elijah",
        lName: "Hawkins",
        email: "elijah.hawkins@eagles.oc.edu",
        idNumber: "1000096",
      }),
      Person.upsert({
        personId: 97,
        fName: "Sarah",
        lName: "Gibson",
        email: "sarah.gibson@eagles.oc.edu",
        idNumber: "1000097",
      }),
      Person.upsert({
        personId: 98,
        fName: "James",
        lName: "Andrews",
        email: "james.andrews@eagles.oc.edu",
        idNumber: "1000098",
      }),
      Person.upsert({
        personId: 99,
        fName: "Amelia",
        lName: "Perry",
        email: "amelia.perry@eagles.oc.edu",
        idNumber: "1000099",
      }),
      Person.upsert({
        personId: 100,
        fName: "Mason",
        lName: "Elliot",
        email: "mason.elliot@eagles.oc.edu",
        idNumber: "1000100",
        activeStatus: 0,
      }),
    ]);
    console.log("Persons initialized successfully");
  } catch (error) {
    console.log("Initialization failed:", error);
  }
}

module.exports = { initializePersons };
