const db = require("../models");
const userRole = db.userRole;

async function initializeUserRole() {
  try {
    await Promise.all([
      await userRole.upsert({
        name: "Admin",
        categoryId: 4,
        canAdd: true,
        canEdit: true,
        canArchive: true,
        canActivate: true,
        canDelete: true,
        viewCheckOutIn: true,
        viewServices: true,
        viewMaintenance: true,
        viewWarranties: true,
        viewLeases: true,
        viewReports: true,
        viewManage: true,
        viewAssets: true,
        viewFacilities: true,
        viewPeople: true,
        viewUsers: true,
        isAdmin: true,
        isManager: false,
        isWorker: false,
        isUnassigned: false
      }),
      await userRole.upsert({
        name: "Unassigned",
        categoryId: null,
        canAdd: false,
        canEdit: false,
        canArchive: false,
        canActivate: false,
        canDelete: false,
        viewCheckOutIn: false,
        viewServices: false,
        viewMaintenance: false,
        viewWarranties: false,
        viewLeases: false,
        viewReports: false,
        viewManage: false,
        viewAssets: false,
        viewFacilities: false,
        viewPeople: false,
        viewUsers: false,
        isAdmin: false,
        isManager: false,
        isWorker: false,
        isUnassigned: true
      }),
      await userRole.upsert({
        name: "Maintenance Manager",
        categoryId: 3,
        canAdd: true,
        canEdit: true,
        canArchive: true,
        canActivate: true,
        canDelete: false,
        viewCheckOutIn: true,
        viewServices: true,
        viewMaintenance: true,
        viewWarranties: true,
        viewLeases: true,
        viewReports: true,
        viewManage: true,
        viewAssets: true,
        viewFacilities: true,
        viewPeople: true,
        viewUsers: true,
        isAdmin: false,
        isManager: true,
        isWorker: false,
        isUnassigned: false
      }),
      await userRole.upsert({
        name: "Maintenance Worker",
        categoryId: 3,
        canAdd: false,
        canEdit: false,
        canArchive: false,
        canActivate: false,
        canDelete: false,
        viewCheckOutIn: false,
        viewServices: false,
        viewMaintenance: true,
        viewWarranties: false,
        viewLeases: false,
        viewReports: false,
        viewManage: false,
        viewAssets: false,
        viewFacilities: false,
        viewPeople: false,
        viewUsers: false,
        isAdmin: false,
        isManager: false,
        isWorker: true,
        isUnassigned: false
      }),
      await userRole.upsert({
        name: "IT Manager",
        categoryId: 1,
        canAdd: true,
        canEdit: true,
        canArchive: true,
        canActivate: true,
        canDelete: false,
        viewCheckOutIn: true,
        viewServices: true,
        viewMaintenance: true,
        viewWarranties: true,
        viewLeases: true,
        viewReports: true,
        viewManage: true,
        viewAssets: true,
        viewFacilities: true,
        viewPeople: true,
        viewUsers: true,
        isAdmin: false,
        isManager: true,
        isWorker: false,
        isUnassigned: false
      }),
      await userRole.upsert({
        name: "IT Worker",
        categoryId: 1,
        canAdd: false,
        canEdit: false,
        canArchive: false,
        canActivate: false,
        canDelete: false,
        viewCheckOutIn: false,
        viewServices: false,
        viewMaintenance: true,
        viewWarranties: false,
        viewLeases: false,
        viewReports: false,
        viewManage: false,
        viewAssets: false,
        viewFacilities: false,
        viewPeople: false,
        viewUsers: false,
        isAdmin: false,
        isManager: false,
        isWorker: true,
        isUnassigned: false
      }),
      await userRole.upsert({
        name: "Support Central Manager",
        categoryId: 2,
        canAdd: true,
        canEdit: true,
        canArchive: true,
        canActivate: true,
        canDelete: false,
        viewCheckOutIn: true,
        viewServices: true,
        viewMaintenance: true,
        viewWarranties: true,
        viewLeases: true,
        viewReports: true,
        viewManage: true,
        viewAssets: true,
        viewFacilities: true,
        viewPeople: true,
        viewUsers: true,
        isAdmin: false,
        isManager: true,
        isWorker: false,
        isUnassigned: false
      }),
      await userRole.upsert({
        name: "Support Central Worker",
        categoryId: 2,
        canAdd: false,
        canEdit: false,
        canArchive: false,
        canActivate: false,
        canDelete: false,
        viewCheckOutIn: false,
        viewServices: false,
        viewMaintenance: true,
        viewWarranties: false,
        viewLeases: false,
        viewReports: false,
        viewManage: false,
        viewAssets: false,
        viewFacilities: false,
        viewPeople: false,
        viewUsers: false,
        isAdmin: false,
        isManager: false,
        isWorker: true,
        isUnassigned: false
      }),
    ]);

    console.log("User Role initialized successfully");
  } catch (error) {
    console.log("Initialization failed:", error);
  }
}

module.exports = { initializeUserRole };
